name: Release

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.m2/repository
      #     key: maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Set up Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github", "username": "${{ github.actor }}", "password": "${{ secrets.ENV_GITHUB_TOKEN }}"}]'
      - name: Release
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "git"
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          mvn -B clean release:prepare release:perform -DskipTests
      - name: Print Release Version
        run: 
          echo "Release Version: ${{ env.GITHUB_REF_NAME }}"
      - name: Merge Release to Master
        run: |
          git fetch origin main
          git checkout main && git merge --no-ff origin/release/${{ env.GITHUB_REF_NAME  }} -m "Merge release ${{ env.release_version }} into master"
          git push origin master  